#!/bin/bash
# Nginx Reverse Proxy Module - Pi Server Setup v2
# Local domain routing with Pi-hole integration

set -euo pipefail

readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m'

log_info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $*"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $*"; }

# Config
NGINX_ENABLED="${NGINX_ENABLED:-true}"
DOMAIN_SUFFIX="${DOMAIN_SUFFIX:-.home}"
PI_USER="${PI_USER:-piadmin}"

main() {
    log_info "Starting Nginx Reverse Proxy setup..."
    
    [[ "${NGINX_ENABLED}" != "true" ]] && { log_info "Nginx disabled in config"; return 0; }
    
    install_nginx
    resolve_port_conflicts
    configure_nginx
    test_and_restart
    show_dns_instructions
    
    log_success "Nginx Reverse Proxy setup completed!"
}

install_nginx() {
    log_info "Installing Nginx..."
    
    if command -v nginx >/dev/null 2>&1; then
        log_info "Nginx already installed"
    else
        apt-get update -qq
        DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nginx
    fi
    
    systemctl enable nginx
}

resolve_port_conflicts() {
    log_info "Resolving port 80 conflicts (Pi-hole FTL)..."
    
    # Stop services temporarily
    systemctl stop pihole-FTL 2>/dev/null || true
    systemctl stop nginx 2>/dev/null || true
    systemctl stop lighttpd 2>/dev/null || true
    
    # Pi-hole v6 (TOML)
    local toml_conf="/etc/pihole/pihole.toml"
    local ftl_conf="/etc/pihole/pihole-FTL.conf"
    
    if [[ -f "${toml_conf}" ]]; then
        log_info "Found Pi-hole v6 config, setting web port to 8081..."
        if command -v pihole-FTL >/dev/null 2>&1; then
            pihole-FTL --config webserver.port 8081
        else
            # Manual TOML edit
            if grep -q "\[webserver\]" "${toml_conf}"; then
                sed -i 's/^port\s*=.*/port = 8081/' "${toml_conf}"
            else
                echo -e "\n[webserver]\n  port = 8081" >> "${toml_conf}"
            fi
        fi
        log_success "Pi-hole v6 web port set to 8081"
        
    elif [[ -f "${ftl_conf}" ]]; then
        log_info "Found Pi-hole v5 config, setting web port to 8081..."
        if grep -q "FTLCONF_webserver_port=" "${ftl_conf}"; then
            sed -i 's/^FTLCONF_webserver_port=.*/FTLCONF_webserver_port=8081/' "${ftl_conf}"
        else
            echo "FTLCONF_webserver_port=8081" >> "${ftl_conf}"
        fi
        log_success "Pi-hole v5 web port set to 8081"
        
    else
        # Fallback to lighttpd
        if [[ -f /etc/lighttpd/lighttpd.conf ]]; then
            log_info "Configuring lighttpd to port 8081..."
            sed -i -E 's/^server\.port\s*=\s*80/server.port = 8081/' /etc/lighttpd/lighttpd.conf
            [[ -f /etc/lighttpd/external.conf ]] && sed -i -E 's/server\.port\s*=\s*80/server.port = 8081/' /etc/lighttpd/external.conf
            log_success "Lighttpd moved to port 8081"
        fi
    fi
}

configure_nginx() {
    log_info "Creating Nginx configuration..."
    
    # Remove default site
    rm -f /etc/nginx/sites-enabled/default
    
    # Get local IP
    local ip
    ip=$(hostname -I | awk '{print $1}')
    
    # Create main reverse proxy config
    cat > /etc/nginx/sites-available/reverse-proxy.conf <<EOF
# Pi Server Setup - Nginx Reverse Proxy
# Generated by pi-server-setup v2

# Default catch-all
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    
    root /var/www/html;
    index index.html;
    
    location / {
        try_files \$uri \$uri/ =200;
    }
    
    # Status page
    location /status {
        return 200 '<html><body><h1>Pi Server Gateway</h1><p>Services are running.</p><ul>
<li><a href="http://dashboard.home">Dashboard (Cockpit)</a></li>
<li><a href="http://pi.home">Pi-hole</a></li>
<li><a href="http://n8n.home">n8n Automation</a></li>
<li><a href="http://webmin.home">Webmin</a></li>
<li><a href="http://pdf.home">Stirling PDF</a></li>
<li><a href="http://grafana.home">Grafana</a></li>
<li><a href="http://prometheus.home">Prometheus</a></li>
</ul></body></html>';
        add_header Content-Type text/html;
    }
}

# Cockpit (dashboard.home)
server {
    listen 80;
    listen [::]:80;
    server_name dashboard${DOMAIN_SUFFIX};
    
    location / {
        proxy_pass http://localhost:9091;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 90s;
        proxy_send_timeout 90s;
    }
}

# n8n (n8n.home)
server {
    listen 80;
    listen [::]:80;
    server_name n8n${DOMAIN_SUFFIX};
    
    location / {
        proxy_pass http://localhost:5678;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
}

# Webmin (webmin.home)
server {
    listen 80;
    listen [::]:80;
    server_name webmin${DOMAIN_SUFFIX};
    
    location / {
        proxy_pass https://localhost:10000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_ssl_verify off;
        proxy_read_timeout 90s;
    }
}

# Stirling-PDF (pdf.home)
server {
    listen 80;
    listen [::]:80;
    server_name pdf${DOMAIN_SUFFIX};
    
    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
}

# Pi-hole (pi.home)
server {
    listen 80;
    listen [::]:80;
    server_name pi${DOMAIN_SUFFIX};
    
    # Redirect root to admin
    location = / {
        return 301 http://pi${DOMAIN_SUFFIX}/admin;
    }
    
    location / {
        proxy_pass http://localhost:8081;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 90s;
    }
}

# Grafana (grafana.home)
server {
    listen 80;
    listen [::]:80;
    server_name grafana${DOMAIN_SUFFIX};
    
    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 90s;
    }
}

# Prometheus (prometheus.home)
server {
    listen 80;
    listen [::]:80;
    server_name prometheus${DOMAIN_SUFFIX};
    
    location / {
        proxy_pass http://localhost:9090;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 90s;
    }
}

# Alertmanager (alertmanager.home)
server {
    listen 80;
    listen [::]:80;
    server_name alertmanager${DOMAIN_SUFFIX};
    
    location / {
        proxy_pass http://localhost:9093;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 90s;
    }
}

# Stirling-PDF (alternative: stirling.home)
server {
    listen 80;
    listen [::]:80;
    server_name stirling${DOMAIN_SUFFIX};
    
    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
EOF
    
    # Enable site
    ln -sf /etc/nginx/sites-available/reverse-proxy.conf /etc/nginx/sites-enabled/
    
    # Create simple index page
    cat > /var/www/html/index.html <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pi Server Gateway</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; background: #f5f5f5; }
        .card { background: white; border-radius: 12px; padding: 30px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 15px; }
        .services { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 15px; margin-top: 20px; }
        .service { display: flex; align-items: center; padding: 15px; background: #f8f9fa; border-radius: 8px; text-decoration: none; color: #2c3e50; transition: transform 0.2s, box-shadow 0.2s; }
        .service:hover { transform: translateY(-2px); box-shadow: 0 4px 12px rgba(0,0,0,0.15); }
        .service-icon { font-size: 24px; margin-right: 15px; }
        .note { background: #fff3cd; border: 1px solid #ffeeba; color: #856404; padding: 15px; border-radius: 8px; margin-top: 20px; }
    </style>
</head>
<body>
    <div class="card">
        <h1>🏠 Pi Server Gateway</h1>
        <p>Welcome to your Raspberry Pi server dashboard. Click a service to access it.</p>
        
        <div class="services">
            <a href="http://dashboard.home" class="service"><span class="service-icon">🖥️</span> Dashboard (Cockpit)</a>
            <a href="http://pi.home" class="service"><span class="service-icon">🛡️</span> Pi-hole DNS</a>
            <a href="http://n8n.home" class="service"><span class="service-icon">⚙️</span> n8n Automation</a>
            <a href="http://webmin.home" class="service"><span class="service-icon">🔧</span> Webmin</a>
            <a href="http://pdf.home" class="service"><span class="service-icon">📄</span> Stirling PDF</a>
            <a href="http://grafana.home" class="service"><span class="service-icon">📊</span> Grafana</a>
            <a href="http://prometheus.home" class="service"><span class="service-icon">📈</span> Prometheus</a>
            <a href="http://alertmanager.home" class="service"><span class="service-icon">🚨</span> Alertmanager</a>
        </div>
        
        <div class="note">
            <strong>💡 Note:</strong> These .home domains require Pi-hole DNS configuration.
            Go to <a href="http://pi.home/admin/dns_records.php">Pi-hole Local DNS</a> and add records pointing to this Pi's IP.
        </div>
    </div>
</body>
</html>
EOF
    
    log_success "Nginx configuration created"
}

test_and_restart() {
    log_info "Testing Nginx configuration..."
    
    if nginx -t; then
        log_success "Nginx configuration test passed"
    else
        log_error "Nginx configuration test failed"
        return 1
    fi
    
    log_info "Restarting services..."
    systemctl restart nginx
    
    # Restart Pi-hole FTL (it will use port 8081 now)
    systemctl restart pihole-FTL 2>/dev/null || true
    systemctl restart lighttpd 2>/dev/null || true
    
    # Verify
    sleep 3
    if systemctl is-active --quiet nginx; then
        log_success "Nginx running on port 80"
    else
        log_error "Nginx failed to start"
        systemctl status nginx --no-pager
        return 1
    fi
}

show_dns_instructions() {
    local ip
    ip=$(hostname -I | awk '{print $1}')
    
    cat <<EOF

${YELLOW}==============================================================${NC}
${YELLOW}  IMPORTANT: Configure Local DNS in Pi-hole${NC}
${YELLOW}==============================================================${NC}

For friendly domain names to work, add these records in Pi-hole:

1. Go to: http://${ip}:8081/admin/dns_records.php
   (or http://pi.${DOMAIN_SUFFIX}/admin/dns_records.php if already working)

2. Add the following Local DNS records (all pointing to ${ip}):
EOF
    
    local domains=("dashboard" "pi" "n8n" "webmin" "pdf" "grafana" "prometheus" "alertmanager" "stirling")
    for domain in "${domains[@]}"; do
        echo "   - ${domain}${DOMAIN_SUFFIX}  ->  ${ip}"
    done
    
    cat <<EOF

3. Save and apply.

Alternatively, run this command on the Pi:
  pihole -a hostrecord dashboard${DOMAIN_SUFFIX} ${ip}
  pihole -a hostrecord pi${DOMAIN_SUFFIX} ${ip}
  pihole -a hostrecord n8n${DOMAIN_SUFFIX} ${ip}
  pihole -a hostrecord webmin${DOMAIN_SUFFIX} ${ip}
  pihole -a hostrecord pdf${DOMAIN_SUFFIX} ${ip}
  pihole -a hostrecord grafana${DOMAIN_SUFFIX} ${ip}
  pihole -a hostrecord prometheus${DOMAIN_SUFFIX} ${ip}
  pihole -a hostrecord alertmanager${DOMAIN_SUFFIX} ${ip}
  pihole -a hostrecord stirling${DOMAIN_SUFFIX} ${ip}

${YELLOW}==============================================================${NC}
EOF
}

# Run
main "$@"