#!/bin/bash
# n8n Automation Engine Module - Pi Server Setup v2
# Native Node.js installation with multi-arch support

set -euo pipefail

readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m'

log_info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $*"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $*"; }

# Config
N8N_VERSION="${N8N_VERSION:-1.64.1}"
N8N_PORT="${N8N_PORT:-5678}"
N8N_WEBHOOK_URL="${N8N_WEBHOOK_URL:-http://n8n.home}"
NODEJS_VERSION="${NODEJS_VERSION:-20}"

main() {
    log_info "Starting n8n setup..."
    
    install_nodejs
    install_n8n
    create_service_user
    configure_n8n
    install_systemd_service
    configure_firewall
    
    log_success "n8n setup completed!"
}

install_nodejs() {
    log_info "Installing Node.js ${NODEJS_VERSION}.x..."
    
    if command -v node >/dev/null 2>&1; then
        local current_version
        current_version=$(node -v | sed 's/v//' | cut -d. -f1)
        if [[ "${current_version}" == "${NODEJS_VERSION}" ]]; then
            log_info "Node.js ${NODEJS_VERSION} already installed"
            return 0
        fi
        log_warn "Node.js version mismatch (have v${current_version}, need v${NODEJS_VERSION})"
    fi
    
    # Install NodeSource repository
    apt-get install -y -qq ca-certificates curl gnupg
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODEJS_VERSION}.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
    
    apt-get update -qq
    apt-get install -y -qq nodejs
    
    # Configure npm for resilience
    npm config set fetch-retries 5
    npm config set fetch-retry-mintimeout 20000
    npm config set fetch-retry-maxtimeout 120000
    npm config set prefer-offline true
    
    log_success "Node.js $(node -v) installed"
}

install_n8n() {
    log_info "Installing n8n v${N8N_VERSION}..."
    
    if command -v n8n >/dev/null 2>&1; then
        local installed_version
        installed_version=$(n8n --version 2>/dev/null | head -1 || echo "unknown")
        if [[ "${installed_version}" == "${N8N_VERSION}" ]]; then
            log_info "n8n ${N8N_VERSION} already installed"
            return 0
        fi
        log_info "Updating n8n from ${installed_version} to ${N8N_VERSION}"
    fi
    
    # Install with retry logic
    local max_retries=3
    local retry=0
    local success=false
    
    while [[ ${retry} -lt ${max_retries} ]] && [[ "${success}" == "false" ]]; do
        if npm install -g "n8n@${N8N_VERSION}" 2>&1; then
            success=true
        else
            ((retry++))
            log_warn "npm install failed (attempt ${retry}/${max_retries}), retrying in 10s..."
            sleep 10
        fi
    done
    
    if [[ "${success}" != "true" ]]; then
        log_error "Failed to install n8n after ${max_retries} attempts"
        return 1
    fi
    
    log_success "n8n ${N8N_VERSION} installed"
}

create_service_user() {
    log_info "Creating n8n service user..."
    
    local user="n8n"
    local home="/var/lib/n8n"
    
    if ! id "${user}" &>/dev/null; then
        useradd -r -s /bin/false -m -d "${home}" "${user}"
        log_info "Created user: ${user}"
    else
        log_info "User ${user} already exists"
    fi
    
    # Ensure directory permissions
    mkdir -p "${home}"
    chown -R "${user}:${user}" "${home}"
}

configure_n8n() {
    log_info "Configuring n8n..."
    
    mkdir -p /etc/n8n
    
    cat > /etc/n8n/env <<EOF
# n8n Configuration
# Generated by pi-server-setup v2

# Port
N8N_PORT=${N8N_PORT}

# Webhook URL (for callbacks)
WEBHOOK_URL=${N8N_WEBHOOK_URL}

# Security
N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

# Disable secure cookies (handled by reverse proxy/Tailscale)
N8N_SECURE_COOKIE=false

# Database (SQLite by default)
DB_TYPE=sqlite
DB_SQLITE_DATABASE=/var/lib/n8n/database.sqlite

# Performance
N8N_PAYLOAD_SIZE_MAX=16

# Logging
N8N_LOG_LEVEL=info
N8N_LOG_OUTPUT=console

# Timezone
GENERIC_TIMEZONE=\$(cat /etc/timezone 2>/dev/null || echo "UTC")
EOF
    
    chmod 600 /etc/n8n/env
    chown -R n8n:n8n /etc/n8n
    
    log_success "n8n configuration written"
}

install_systemd_service() {
    log_info "Installing n8n systemd service..."
    
    cat > /etc/systemd/system/n8n.service <<EOF
[Unit]
Description=n8n Automation Engine
Documentation=https://docs.n8n.io
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=n8n
Group=n8n
EnvironmentFile=/etc/n8n/env
WorkingDirectory=/var/lib/n8n

# Use the globally installed n8n
ExecStart=/usr/bin/node /usr/bin/n8n start

# Restart policy
Restart=always
RestartSec=10
TimeoutStartSec=300

# Security hardening
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=strict
ProtectHome=yes
ReadWritePaths=/var/lib/n8n /etc/n8n
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
RestrictRealtime=yes
RestrictNamespaces=yes
LockPersonality=yes
MemoryDenyWriteExecute=yes
SystemCallFilter=@system-service
SystemCallErrorNumber=EPERM

# Resource limits
LimitNOFILE=65536
LimitNPROC=512
MemoryMax=1G
CPUQuota=80%

[Install]
WantedBy=multi-user.target
EOF
    
    systemctl daemon-reload
    systemctl enable n8n
    systemctl restart n8n
    
    # Verify
    sleep 5
    if systemctl is-active --quiet n8n; then
        log_success "n8n service running on port ${N8N_PORT}"
    else
        log_error "n8n service failed to start"
        systemctl status n8n --no-pager
        return 1
    fi
}

configure_firewall() {
    if command -v ufw >/dev/null 2>&1 && ufw status | grep -q "Status: active"; then
        log_info "Configuring UFW for n8n..."
        ufw allow "${N8N_PORT}/tcp" comment "n8n" || true
        log_success "Firewall rule added"
    fi
}

# Run
main "$@"